version: "3.8"


services:
  web:
    container_name: mini_umbrella_api
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - pg_admin


  postgres:
    container_name: postgres_db
    image: postgres:13-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: miniumbrelladb
      PGDATA: /var/lib/postgresql/data/
    restart: always


  pg_admin:
    container_name: pgadmin_gui
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL : admin@admin.com
      PGADMIN_DEFAULT_PASSWORD : admin
      PGADMIN_LISTEN_PORT : 80
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: always
    logging:
      driver: none


volumes:
  postgres:
  pgadmin:
