version: "3.8"

services:
  web:
    container_name: mini_umbrella_api
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  redis:
    container_name: cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  postgres:
    container_name: postgres_db
    image: postgres:13-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: miniumbrelladb
      PGDATA: /var/lib/postgresql/data/
    restart: always


volumes:
  cache:
    driver: local
  postgres:


networks:
  app-tier:
    driver: bridge